spring:
  application:
    name: department-service
  profiles:
    active: ${env}

#admin client config
management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"